### ISSUE TITLE
Setup CD

### ISSUE THREAD

**Issue by Akarys42** [gustavwilliam/bestpy#10]
# Abstract
Let’s be honest, the maintainers are lazy, let’s automate the release. 

# Possible triggers
1. When a tag is pushed
2. When a GitHub Release is created
3. When a push to a release branch is done (could also be a merged PR)
4. Manual Actions trigger

# Implementation details
A GitHub Actions workflow would trigger, package everything, and push it to PyPi. 
Two secrets will have to be added: `PYPI_USERNAME` and `PYPI_PASSWORD`. 

# Additional details 
This can also be used to setup a nightly release, as proposed in #7.

**Comment by gustavwilliam** [comment]
I think this sounds good, though I don't have much experience managing releases. However, I think a release branch and/or GitHub releases sounds good. We probably don't want to make a new release for every push. What do you think?

**Comment by Akarys42** [comment]
Yeah, the idea would be to trigger it when a push is done to a specific
branch, so only when a PR from the development branch (for instance master)
is merged to to release, so it will contain many contributions in the new
release.

**Comment by gustavwilliam** [comment]
That sounds perfect! How do you think is a good way to do the branching? Like CPython with master (main) as the development branch and maintenance versions on separate branches? Or maybe some other way?

**Comment by Akarys42** [comment]
Since PyPi uses a linear history, you can’t (and probably won’t need) any
backport, so my idea would be to merge from feature branches or forks to
main that’d act as a development branch, and when a release is ready to be
pushed merge it with release, and that will trigger a release, create a tag
and whatnot

**Comment by gustavwilliam** [comment]
That sounds a lot like the CPython way of doing things as well. I like it.

Would you like to work on this CD? It sounds like you know much more than I on this topic.

**Comment by Akarys42** [comment]
Sure thing!

**Comment by gustavwilliam** [comment]
Awesome; thanks! Keep me posted.

**Comment by vivax3794** [comment]
are we going to just use the normal setuptools, or maybe a tool like [poetry](https://python-poetry.org/)?

**Comment by gustavwilliam** [comment]
Maybe keeping it simple would be nice for now. Any reasons we would use Poetry?

**Comment by vivax3794** [comment]
it makes it simple to push to PyPi and can also take care of managing development dependencies (like flake8 and pytest)

**Comment by vivax3794** [comment]
but as @Akarys42 is the one planning to do this I think we can go with whatever they decide

**Comment by gustavwilliam** [comment]
> are we going to just use the normal setuptools, or maybe a tool like [poetry](https://python-poetry.org/)?

Update: after a discussion about possible ways of managing dependencies, we decided that Poetry will probably be used.

**Comment by vivax3794** [comment]
since we are using poetry I am going to link the docs for the poetry publish command: <https://python-poetry.org/docs/cli/#publish> (will also need to [build](https://python-poetry.org/docs/cli/#build) first)
