### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by vivax3794** [gustavwilliam/bestpy#12]
# Framwork
we could use the built-in [unittest](https://docs.python.org/3/library/unittest.html) to keep with the current no depends, but I **really** like [pytest](https://docs.pytest.org/en/latest/).

when the tests have been setup they should be used with #8 as well.

I would be more than happy to write the tests

**Comment by vivax3794** [comment]
> to keep with the current no depends

on second thought, pytest would be a development dependency anyway, as so will flake8 and so be when that is setup

**Comment by gustavwilliam** [comment]
That would be cool. What do you think we should have tests for?

I don't have a strong preference about whether to use such dependencies or not. Either way would work imo.

**Comment by vivax3794** [comment]
everything? haha. `add_from_class`, methods added to `CodeAnswers`

**Comment by gustavwilliam** [comment]
I mean, sure thing. Unit tests are very nice 😄

We should probably wait for the package logic to move from the main file to init first, though. After that, I'm all for it.

**Comment by fisher60** [comment]
I am fairly biased to pytest, I find it looks much cleaner.

**Comment by gustavwilliam** [comment]
Then I see no reason to use anything else. Let's go with PyTest!

**Comment by vivax3794** [comment]
great I can start work on it when #15 and #16 get merged

**Comment by gustavwilliam** [comment]
@vivax3794 we should be ready to start writing tests!

We're considering changing the way that answers are stored, but that shouldn't change the outputs of using the package in any way.

Thanks for helping out.
