### ISSUE TITLE
Updating the storage of answers

### ISSUE THREAD

**Issue by gustavwilliam** [gustavwilliam/bestpy#19]
@SuperMaZingCoder proposed changing the system that we use to store answers, and using JSON (@fisher60 proposed YAML) for it. The main benefit would be not keeping a huge dictionary of items in memory at all times, it seems.

Could we formalize this discussion a bit, and try to keep it in one place — this issue? Maybe we can decide on an implementation.

**Comment by Qwerty-133** [comment]
I don't think there are a lot of items inside the dict at all. I believe storing in JSON would only be beneficial if we plan on scaling this by a lot.

Talking about this, #23 could help lessen the memory the dict consumes.

**Comment by gustavwilliam** [comment]
Thanks for the comment! We're planning on expanding the list by a lot and possibly splitting categories into multiple files. Maybe changing the storage format would be something to do later on, if it expands so much. We already have ranges and such python-specific things, so it would be *nice* to have it in python files.

Maybe splitting it into multiple files should be the next step. What do you think @Qwerty-133?

**Comment by gustavwilliam** [comment]
I think using Python files for the answers is definitely good enough for now, especially considering some of the features I explained in the last comment.
