### ISSUE TITLE
best.py or bestpy

### ISSUE THREAD

**Issue by gustavwilliam** [gustavwilliam/bestpy#2]
Should we call this `best.py` or `bestpy`? They both have their pros and cons.

@fisher60 what do you think?

**Comment by fisher60** [comment]
Hmmmm, I feel that `best.py` is a bit arrogant, but I certainly do not want or files to be `bestpy.py`.

I am leaning towards `best.py`, but I also despise when packages have a different import than their package name/`pip install`, so we would need to ensure we can get the name.

**Comment by gustavwilliam** [comment]
True. Since `best` is already taken on PyPi, `bestpy` may actually be our best option. Let's go with that. At least for now.
