### ISSUE TITLE
Best way to store answers

### ISSUE THREAD

**Issue by gustavwilliam** [gustavwilliam/bestpy#3]
It was discussed how to best store the answers in a way that is clean, effective and allows for flexibility. We want to allow static ans random answers, as well as ones that require code execution on every access.

Here's a possible implementation:
```py
class CodeAnswers:
    @staticmethod
    def os():
        name = platform.system()

        # Replacing "Darwin", since it might be confusing for macOS users
        if name == "Darwin":
            name = "macOS"

        return name


answers = {
    "language": "Python",
    "package": "Bestpy",
    "os": CodeAnswers.os,
    "year": list(range(2100)),
}
```
The `answers` dict allows us to have a single source of truth. These are the basic types that I expect the values to accept:
- Strings
- Numeric values
- Lists
- Functions

Strings and numbers will simply be returned when the user runs `best.CATEGORY`. For lists, one of the items is randomly chosen. For functions, the function is run and the return value is treated like any other value. The example answers list given in the code above illustrates all basic types.

**Comment by fisher60** [comment]
This implementation looks good to me, I say we go ahead with this, then see how it fits our needs.

**Comment by gustavwilliam** [comment]
Sounds good!
