### ISSUE TITLE
Improve README Examples

### ISSUE THREAD

**Issue by HassanAbouelela** [gustavwilliam/bestpy#6]
The current README uses this example twice:
```py
>>> best.language
"python"
>>> best.module
"bestpy"
```

The best Readme should provide a multitude of the best examples, to give the best help possible to new and experienced users alike.

**Comment by gustavwilliam** [comment]
Thanks for the issue. I agree about it and will change it to something else.

**Comment by gustavwilliam** [comment]
Done!
